analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - lib/**/*.g.dart
enable-experiment:
  - extension-methods
linter:
  rules:
  - empty_statements
  - invariant_booleans
  - control_flow_in_finally
  - avoid_returning_null_for_future
  - avoid_relative_lib_imports
  - literal_only_boolean_expressions
  - no_adjacent_strings_in_list
  - no_duplicate_case_values
  - prefer_void_to_null
  - throw_in_finally
  - unnecessary_statements
  - always_put_control_body_on_new_line
  - always_put_required_named_parameters_first
  - always_require_non_null_named_parameters
  - avoid_as
  - avoid_bool_literals_in_conditional_expressions
  - avoid_catches_without_on_clauses
  - avoid_catching_errors
  - avoid_classes_with_only_static_members
  - avoid_double_and_int_checks
  - avoid_field_initializers_in_const_classes
  - avoid_null_checks_in_equality_operators
  - avoid_positional_boolean_parameters
  - avoid_private_typedef_functions
  - avoid_renaming_method_parameters
  - avoid_return_types_on_setters
  - avoid_returning_null
  - avoid_returning_null_for_void
  - avoid_returning_this
  - avoid_setters_without_getters
  - avoid_shadowing_type_parameters
  - avoid_single_cascade_in_expression_statements
  - avoid_types_on_closure_parameters
  - avoid_unused_constructor_parameters
  - await_only_futures
  - cascade_invocations
  - curly_braces_in_flow_control_structures
  - directives_ordering
  - empty_catches
  - file_names
  - flutter_style_todos
  - implementation_imports
  - join_return_with_assignment
  - lines_longer_than_80_chars
  - non_constant_identifier_names
  - null_closures
  - omit_local_variable_types
  - only_throw_errors
  - overridden_fields
  - parameter_assignments
  - prefer_adjacent_string_concatenation
  - prefer_asserts_in_initializer_lists
  - prefer_collection_literals
  - prefer_conditional_assignment
  - prefer_const_declarations
  - prefer_const_literals_to_create_immutables
  - prefer_constructors_over_static_methods
  - prefer_contains
  - prefer_equal_for_default_values
  - prefer_final_fields
  - prefer_final_locals
  - prefer_foreach
  - prefer_function_declarations_over_variables
  - prefer_initializing_formals
  - prefer_interpolation_to_compose_strings
  - prefer_is_empty
  - prefer_is_not_empty
  - prefer_iterable_whereType
  - prefer_mixin
  - prefer_single_quotes
  - prefer_typing_uninitialized_variables
  - recursive_getters
  - slash_for_doc_comments
  - sort_constructors_first
  - sort_unnamed_constructors_first
  - type_init_formals
  - unawaited_futures
  - unnecessary_await_in_return
  - unnecessary_brace_in_string_interps
  - unnecessary_const
  - unnecessary_getters_setters
  - unnecessary_lambdas
  - unnecessary_new
  - unnecessary_null_aware_assignments
  - unnecessary_null_in_if_null_operators
  - unnecessary_overrides
  - unnecessary_parenthesis
  - unnecessary_this
  - use_function_type_syntax_for_parameters
  - use_rethrow_when_possible
  - use_setters_to_change_properties
  - use_string_buffers
  - use_to_and_as_if_applicable
  - void_checks
  - package_names
  - iterable_contains_unrelated_type
  - list_remove_unrelated_type
  - test_types_in_equals
  - unrelated_type_equality_checks
  - valid_regexps
  - hash_and_equals
  - avoid_empty_else
  - cancel_subscriptions
  - close_sinks
  - always_declare_return_types
  - camel_case_types
  - empty_constructor_bodies
  - annotate_overrides
  - avoid_init_to_null
  - constant_identifier_names
  - one_member_abstracts