version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'
